import os

TFLITE_DIR = "./tflite"
OUTPUT_DIR = "./esp32/models"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Models to convert: (tflite filename, c variable name, header filename)
MODELS = [
    ("tcn_int8.tflite",       "tcn_int8",       "tcn_int8_model.h"),
    ("cnn_float16.tflite",    "cnn_float16",    "cnn_float16_model.h"),
    ("cnn_qat_int8.tflite",   "cnn_qat_int8",   "cnn_qat_int8_model.h"),
]


def tflite_to_c_header(tflite_path, var_name, output_path):
    with open(tflite_path, 'rb') as f:
        data = f.read()

    size_kb = len(data) / 1024

    # Format as C byte array — 12 bytes per line for readability
    hex_bytes = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(hex_bytes), 12):
        line = "  " + ", ".join(hex_bytes[i:i+12]) + ","
        lines.append(line)

    c_array = "\n".join(lines)
    # Remove trailing comma on last line
    c_array = c_array.rstrip(",\n") + "\n"

    header = f"""// Auto-generated by convert_to_c_array.py
// Source: {os.path.basename(tflite_path)}
// Size:   {size_kb:.1f} KB ({len(data)} bytes)

#ifndef {var_name.upper()}_MODEL_H
#define {var_name.upper()}_MODEL_H

#include <stdint.h>

// Align to 8 bytes — required by TFLite Micro
alignas(8) const uint8_t {var_name}_model_data[] = {{
{c_array}}};

const unsigned int {var_name}_model_data_len = {len(data)};

#endif // {var_name.upper()}_MODEL_H
"""

    with open(output_path, 'w') as f:
        f.write(header)

    print(f"  Saved: {output_path}  ({size_kb:.1f} KB, {len(data)} bytes)")
    return len(data)


# ─────────────────────────────────────────────
# MAIN — Convert all models
# ─────────────────────────────────────────────
print("=" * 50)
print("TFLite → C Header Conversion")
print("=" * 50)

converted = []
for tflite_name, var_name, header_name in MODELS:
    tflite_path = os.path.join(TFLITE_DIR, tflite_name)
    output_path = os.path.join(OUTPUT_DIR, header_name)

    if not os.path.exists(tflite_path):
        print(f"\n  [!] Skipping {tflite_name} — file not found")
        continue

    print(f"\nConverting {tflite_name}...")
    size = tflite_to_c_header(tflite_path, var_name, output_path)
    converted.append((var_name, header_name, size))

# ─────────────────────────────────────────────
# Print usage instructions
# ─────────────────────────────────────────────
print("\n" + "=" * 50)
print("DONE — Files saved to ./esp32/models/")
print("=" * 50)
print("\nTo use in your ESP32 sketch:")
print()
for var_name, header_name, size in converted:
    print(f"  #include \"models/{header_name}\"")
print()
print("  // Then pass to TFLM interpreter:")
for var_name, _, _ in converted:
    print(f"  // const uint8_t* model_data = {var_name}_model_data;")
    print(f"  // unsigned int   model_len  = {var_name}_model_data_len;")
    print()

print("\nNext step: Arduino IDE setup for ESP32 + TFLite Micro")