import os

import numpy as np


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = os.path.join(BASE_DIR, "esp32", "arrhythmia_inference", "test_samples.h")
SAMPLES_PER_CLASS = 2
CLASS_NAMES = ["Normal", "APC", "PVC", "Fusion"]

os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)


def resolve_processed_dir():
    candidates = [
        os.environ.get("PROCESSED_DIR"),
        os.path.join(BASE_DIR, "processed"),
        os.path.join(
            BASE_DIR,
            "mit-bih-arrhythmia-database-1.0.0",
            "mit-bih-arrhythmia-database-1.0.0",
            "processed",
        ),
    ]

    for candidate in candidates:
        if candidate and os.path.exists(os.path.join(candidate, "X_test.npy")):
            return candidate

    raise FileNotFoundError(
        "Could not find processed data. Set PROCESSED_DIR or place the .npy files "
        "under ./processed or the nested dataset folder."
    )


processed_dir = resolve_processed_dir()
X_test = np.load(os.path.join(processed_dir, "X_test.npy"))
y_test = np.load(os.path.join(processed_dir, "y_test.npy"))

selected_X = []
selected_y = []

for cls in range(4):
    indices = np.where(y_test == cls)[0][:SAMPLES_PER_CLASS]
    for index in indices:
        selected_X.append(X_test[index, :, 0])
        selected_y.append(cls)

selected_X = np.array(selected_X, dtype=np.float32)
selected_y = np.array(selected_y, dtype=np.int32)
num_samples = len(selected_X)

print(f"Loaded processed data from: {processed_dir}")
print(f"Embedding {num_samples} test samples ({SAMPLES_PER_CLASS} per class)")

lines = []
lines.append("// Auto-generated by test_beats.py")
lines.append("// Contains real MIT-BIH beats for on-device testing")
lines.append("")
lines.append("#ifndef TEST_SAMPLES_H")
lines.append("#define TEST_SAMPLES_H")
lines.append("")
lines.append(f"#define NUM_TEST_SAMPLES {num_samples}")
lines.append("#define SAMPLE_LENGTH    187")
lines.append("")
lines.append(f"const float test_samples[{num_samples}][187] = {{")

for sample_index, sample in enumerate(selected_X):
    class_id = selected_y[sample_index]
    class_name = CLASS_NAMES[class_id]
    lines.append(f"  // Sample {sample_index} - Class {class_id} ({class_name})")
    lines.append("  {")

    values = [f"{value:.6f}f" for value in sample]
    for start in range(0, len(values), 8):
        lines.append("    " + ", ".join(values[start : start + 8]) + ",")

    lines.append("  },")

lines.append("};")
lines.append("")
label_values = ", ".join(str(label) for label in selected_y)
lines.append(f"const int test_labels[{num_samples}] = {{{label_values}}};")
lines.append("")
lines.append("#endif // TEST_SAMPLES_H")

with open(OUTPUT_PATH, "w") as file_obj:
    file_obj.write("\n".join(lines))

print(f"Saved: {OUTPUT_PATH}")
print(f"Samples: {[CLASS_NAMES[label] for label in selected_y]}")
